use serde::Serialize;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TokenUsage {
    pub input_tokens: i64,
    pub cached_input_tokens: i64,
    pub output_tokens: i64,
    pub reasoning_output_tokens: i64,
    pub total_tokens: i64,
}

impl TokenUsage {
    pub(crate) fn has_negative_delta_from(self, previous: Self) -> bool {
        self.input_tokens < previous.input_tokens
            || self.cached_input_tokens < previous.cached_input_tokens
            || self.output_tokens < previous.output_tokens
            || self.reasoning_output_tokens < previous.reasoning_output_tokens
            || self.total_tokens < previous.total_tokens
    }

    pub(crate) fn saturating_delta_from(self, previous: Self) -> Self {
        Self {
            input_tokens: self.input_tokens - previous.input_tokens,
            cached_input_tokens: self.cached_input_tokens - previous.cached_input_tokens,
            output_tokens: self.output_tokens - previous.output_tokens,
            reasoning_output_tokens: self.reasoning_output_tokens
                - previous.reasoning_output_tokens,
            total_tokens: self.total_tokens - previous.total_tokens,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UsageDimension {
    pub key: String,
    pub label: String,
    pub usage: TokenUsage,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct LocalUsageSummary {
    pub generated_at: String,
    pub source_files: i64,
    pub indexed_events: i64,
    pub skipped_events: i64,
    pub filtered_parent_events: i64,
    pub total: TokenUsage,
    pub today: TokenUsage,
    pub by_model: Vec<UsageDimension>,
    pub by_project: Vec<UsageDimension>,
    pub warnings: Vec<String>,
}

/// One locally derived, canonical usage event. `task_key` is an irreversible
/// hash generated by the index; no rollout id, path, prompt, response, or
/// conversation title is exposed.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct LocalUsageEvent {
    pub task_key: String,
    pub occurred_at_ms: Option<i64>,
    pub model_label: String,
    pub project_label: String,
    pub usage: TokenUsage,
    /// True only when this source supplied the cache components needed for a
    /// cache-hit calculation. It never exposes the raw source record.
    pub cache_metrics_available: bool,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FileScanReport {
    /// Opaque local identifier. This is not a rollout/thread id or a path.
    pub file_id: i64,
    pub complete_lines_added: i64,
    pub indexed_events_added: i64,
    pub committed_offset: i64,
    pub incomplete_tail: bool,
    pub reset: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanSummary {
    pub discovered_files: usize,
    pub changed_files: usize,
    pub indexed_events_added: i64,
    pub incomplete_files: usize,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct Attribution {
    pub model_key: String,
    pub model_label: String,
    pub project_key: Vec<u8>,
    pub project_label: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum OwnershipMode {
    All,
    Ordinal,
    LegacyMarker,
    Unresolved,
}

impl OwnershipMode {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::All => "all",
            Self::Ordinal => "ordinal",
            Self::LegacyMarker => "legacy-marker",
            Self::Unresolved => "unresolved",
        }
    }

    pub(crate) fn parse(value: &str) -> Option<Self> {
        match value {
            "all" => Some(Self::All),
            "ordinal" => Some(Self::Ordinal),
            "legacy-marker" => Some(Self::LegacyMarker),
            "unresolved" => Some(Self::Unresolved),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct ParserState {
    pub first_record_seen: bool,
    pub next_history_ordinal: i64,
    pub is_subagent: bool,
    pub ownership_mode: OwnershipMode,
    pub boundary_ordinal: Option<i64>,
    pub owned: bool,
    pub current: Attribution,
    pub legacy_candidate: Option<Attribution>,
    pub previous_total: Option<TokenUsage>,
    pub last_fallback_pending: bool,
    pub skipped_events: i64,
    pub filtered_parent_events: i64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum UsageSource {
    TotalDelta,
    TotalSegmentStart,
    LastFallback,
}

impl UsageSource {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::TotalDelta => "total-delta",
            Self::TotalSegmentStart => "total-segment-start",
            Self::LastFallback => "last-fallback",
        }
    }
}

#[derive(Clone, Debug)]
pub(crate) struct PendingUsageEvent {
    pub logical_key: Vec<u8>,
    pub source_ordinal: Option<i64>,
    pub source_line: i64,
    pub end_offset: i64,
    pub occurred_at_ms: Option<i64>,
    pub source: UsageSource,
    pub attribution: Attribution,
    pub usage: TokenUsage,
    pub cache_metrics_available: bool,
    pub payload_hash: Vec<u8>,
}

#[derive(Clone, Debug)]
pub(crate) struct ParseEffects {
    pub event: Option<PendingUsageEvent>,
    pub warning_codes: Vec<&'static str>,
}

impl ParseEffects {
    pub(crate) fn empty() -> Self {
        Self {
            event: None,
            warning_codes: Vec::new(),
        }
    }
}
